env: "local" # local dev prod
storage_path: "./storage/storage.db"
http_server:
  address: ":3000"
  timeout: 4s
  idle_timeout: 60s
storage:
  host: postgres #localhost
  port: 5432 #5434
  database: library
  username: admin
  password: admin